//defines.h

#define SETBIT(WORD,BITPOS) 	WORD|=1<<BITPOS
#define READWRITEBIT(DWORD,DBIT,SWORD,SBIT) \
        DWORD=((DWORD&~(1<<DBIT))|(((SWORD>>SBIT)&1)<<DBIT))

#define READBIT(WORD,BITPOS) ((WORD>>BITPOS)&1)
#define WRITEBIT(WORD,BITPOS,BITLEVEL) \
        WORD=((WORD&~(1<<BITPOS))|(BITLEVEL<<BITPOS))
#define WRITEBYTE(WORD,BITPOS,VAL)\
         WORD=((WORD&~(0xFF<<BITPOS))|(VAL<<BITPOS))
#define WRITENIBBLE(WORD,BITPOS,VAL)\
         WORD=((WORD&~(0xF<<BITPOS))|(VAL<<BITPOS))
#define READNIBBLE(WORD,BITPOS)\
         ((WORD>>BITPOS)&0xF)
